In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
import tensorflow as tf
import os
import librosa as lbrs
import wave as wv
import glob
import audioread as ar
import binascii

In [18]:
path = "C:\\Users\\yioua\\Documents\\UCSC\\Deep Learning and Artificial Intelligence with TensorFlow\\Final Project\\dl_music\\genres"

In [19]:
glob.glob(path + "\\*\\")

['C:\\Users\\yioua\\Documents\\UCSC\\Deep Learning and Artificial Intelligence with TensorFlow\\Final Project\\dl_music\\genres\\blues\\',
 'C:\\Users\\yioua\\Documents\\UCSC\\Deep Learning and Artificial Intelligence with TensorFlow\\Final Project\\dl_music\\genres\\classical\\',
 'C:\\Users\\yioua\\Documents\\UCSC\\Deep Learning and Artificial Intelligence with TensorFlow\\Final Project\\dl_music\\genres\\country\\',
 'C:\\Users\\yioua\\Documents\\UCSC\\Deep Learning and Artificial Intelligence with TensorFlow\\Final Project\\dl_music\\genres\\disco\\',
 'C:\\Users\\yioua\\Documents\\UCSC\\Deep Learning and Artificial Intelligence with TensorFlow\\Final Project\\dl_music\\genres\\hiphop\\',
 'C:\\Users\\yioua\\Documents\\UCSC\\Deep Learning and Artificial Intelligence with TensorFlow\\Final Project\\dl_music\\genres\\jazz\\',
 'C:\\Users\\yioua\\Documents\\UCSC\\Deep Learning and Artificial Intelligence with TensorFlow\\Final Project\\dl_music\\genres\\metal\\',
 'C:\\Users\\yioua\\D

In [20]:
import audioread as ar
file = path+"\\blues\\blues.00000.au"
with ar.audio_open(file) as f:
    i=0
    print(f.channels, f.samplerate, f.duration)
    for buf in f:
        i+=1
    print(i)

1 22050 30.013333333333332
647


In [108]:
# Read the file

for e in glob.glob(path + "\\*"):
    count = 0
    for e2 in glob.glob(e + "\\*"):
        print(e2)
        count+=1
        with ar.audio_open(e2) as f:
            print(f.channels, f.samplerate, f.duration)
            i=0
            l = 0
            data = []
            for buf in f:
                i+=1
                l+=len(buf)
                #print(len(buf))
                #count2 = 0
                for e3 in buf:
                    #count2+=1
                    data.append(e3)
                    #print(e3)
                    #if (count2>5):
                    #    break
                #print("test")
                #print(buf)
                #break
                #print(len(buf))
                #if len(buf) > l:
                #    print(len(buf))
            print(i,l)
            data = np.array(data)
            data.resize(i,2048,refcheck=False)
            print(data,data.shape, len(data[0]), data[i-1][575:585])
            #print(len(data))
            break
    #Stop the loop after 5 elements
    if (count>5):
        break

C:\Users\yioua\Documents\UCSC\Deep Learning and Artificial Intelligence with TensorFlow\Final Project\dl_music\genres\blues\blues.00000.au
1 22050 30.013333333333332
647 1323588
[[240   0  32 ... 254 247 254]
 [101 253 101 ... 251  14 248]
 [ 47 247  47 ...   3 115   5]
 ...
 [ 76 248 201 ... 243 220 242]
 [ 21 245 244 ...  20  94  19]
 [199  10 148 ...   0   0   0]] (647, 2048) 2048 [248  47 248 201 247   0   0   0   0   0]
C:\Users\yioua\Documents\UCSC\Deep Learning and Artificial Intelligence with TensorFlow\Final Project\dl_music\genres\classical\classical.00000.au
1 22050 30.013333333333332
647 1323588
[[110 253 195 ...   4 137   4]
 [ 98   3 206 ... 254  14 255]
 [  9   0 110 ... 252 174 253]
 ...
 [241 255 223 ...   1 197   1]
 [ 90   1 133 ...   2 222   2]
 [ 57   3 245 ...   0   0   0]] (647, 2048) 2048 [  2 142   3   2   4   0   0   0   0   0]
C:\Users\yioua\Documents\UCSC\Deep Learning and Artificial Intelligence with TensorFlow\Final Project\dl_music\genres\country\country.

In [116]:
"""Gather all the data into one list, which is a list of tuple composed of the file read as an list of bytes, 
the size of the buffer and the number of buffers"""
alldata = []

#For each directory
count = 0
for dir_name in glob.glob(path + "\\*"):
    #for each file in the directory
    for file_name in glob.glob(dir_name + "\\*"):
        #read the file into data
        with ar.audio_open(file_name) as f:
            nb_of_buffer = 0
            size_of_file = 0
            data = []
            for buf in f:
                nb_of_buffer+=1
                size_of_file+=len(buf)
                for buf_element in buf:
                    data.append(buf_element)
            size_of_buffer = size_of_file//(nb_of_buffer-1)
            alldata.append((data, size_of_buffer, nb_of_buffer))
    count+=1
    # Ok, this is taking a while to do, and it is only about 40% of the data...
    if count>3:
        break

print(len(alldata))
(d1, size1, nb1) = alldata[0]
print(len(d1), size1, nb1)

400
1323588 2048 647


In [110]:
1323588//646

2048